resources:
- autoscaler.yaml
- ../../application
images:
- name: argo-app-backend
  newName: brechtcox/backend-todo-app-herexamen
  newTag: v4.0.1
- name: argo-app-frontend
  newName: brechtcox/frontend-todo-app-herexamen
  newTag: v4.0.2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
