resources:
- autoscaler.yaml
- ../../application
images:
- name: argo-app-backend
  newName: brechtcox/backend-todo-app-examen
  newTag: v2.2.0
- name: argo-app-frontend
  newName: brechtcox/frontend-todo-app-herexamen
  newTag: v1.0.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
