apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  labels:
    name: actions-runner-system
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
type: Opaque
data:
  github_token: Z2hwX2VkR3hCTzRrOGJVOGxnZll