apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: argo-app-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "40m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: DBURL
          valueFrom:
            configMapKeyRef:
              name: mongo-url
              key: database-uri
        - name: PORT
          value: "8080"
      serviceAccountName: webapp-manager
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
