apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: webapp-permissions
rules:
- apiGroups: 
  - ""
  resources: 
  - pods
  verbs: 
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: 
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: 
  - list
  - watch
  - get